Add P2P, PoS and ECDSA via secp256k1
peerbridge/peerbridge pull request #19
Opened 2021-03-19 14:54 UTC by PhilippMatthes

2021-03-26 12:12 UTC, PhilippMatthes commented
@felix-kaestner there has been so much work on this PR, might as well merge it for now to not fully detach the main branch from this development branch. There are still some minor things that need to be implemented, such as:

- Improve the stability of the consensus between multiple nodes
- Receive new transactions and include them into the blocks (currently only the genesis blocks have transactions)
- Remove the time.Time wrapper, since time is now handled via Unix nanoseconds
- Some other minor implementations and documentation changes (Add the new routes and instructions to the readme)

Feel free to give me some feedback on whether you want to merge this PR for now and include the minor improvements later on, or if this should stay detached until all remaining issues are implemented.

2021-03-26 18:17 UTC, felix-kaestner requested changes
Overall really impressive work. Thank you!

2021-03-26 18:17 UTC, felix-kaestner commented on pkg/blockchain/tree.go
> +	StemNodes *[]*BlockTree
A pointer to a slice of pointers seems really bad.

2021-03-26 18:17 UTC, felix-kaestner commented on pkg/blockchain/tree.go
> +func (root *BlockTree) Chop(length int) (*BlockTree, *ChopResult, error) {
Maybe we could use other terminology then `Chop`, this always reminds be of chopping wood.

2021-03-26 18:17 UTC, felix-kaestner commented on pkg/blockchain/tree.go
> +}
Same as before, functions should be merged.

2021-03-26 18:17 UTC, felix-kaestner commented on pkg/color/color.go
> +}
I actually don't understand the purpose of this function and why it is placed inside the color package.

2021-03-26 18:17 UTC, felix-kaestner commented on pkg/http/error.go
> +	log.Println(err.Error())
I don't think there should be an error in a response with status code 202

2021-03-26 19:33 UTC, PhilippMatthes commented on pkg/blockchain/block.go
> +	ParentID *encryption.SHA256HexString `json:"parentID" sign:"yes"`
The idea behind this is that the ParentID can be nil for the genesis block, which is not allowed for non-reference values as far as I understood it

2021-03-26 19:34 UTC, PhilippMatthes commented on pkg/blockchain/block.go
> +func (block *Block) AccountBalance(p secp256k1.PublicKeyHexString) int64 {
Yes, the genesis account (due to the genesis transactions which grant initial account balances) has a negative account balance. For every other account it should be validated that a transaction does not lead to a fall of the account balance to below 0.

2021-03-26 19:36 UTC, PhilippMatthes commented on pkg/blockchain/block.go
> +	bytes, err := json.MarshalIndent(values, "", "  ")
The idea behind this is to specify the indent, so that it is definite how the json is formatted. If somebody implements the peebridge protocol with another technology (or within our messenger apps) it should be explicit how the json is indented, since the signature is dependent on that

2021-03-26 19:38 UTC, PhilippMatthes commented on pkg/blockchain/chain.go
> +}
Yes, indeed. This makes it more lasagne-like. Will refactor this so that the id based function is used

2021-03-26 19:39 UTC, PhilippMatthes commented on pkg/blockchain/chain.go
> +	return nil, errors.New("Transaction not found!")
It would be easier to simply declare variables for the specific errors, as I have seen that in some go libraries. Will do this, and you can check back later to see what I mean

2021-03-26 19:43 UTC, PhilippMatthes commented on pkg/blockchain/routes.go
> +	router.Get("/transaction/get", getTransaction)
Tried this but it did fail with an error that two methods were assigned to the same url.

2021-03-26 19:45 UTC, PhilippMatthes commented on pkg/color/color.go
> +}
This is a remnant of my debugging approaches to printing out blocks with a specific color in the command line. Since I removed the printtree method, this is not needed

2021-03-26 19:46 UTC, PhilippMatthes commented on pkg/blockchain/tree.go
> +func (root *BlockTree) Chop(length int) (*BlockTree, *ChopResult, error) {
That was actually my intention since we are chopping the head tree

2021-03-26 19:48 UTC, PhilippMatthes commented
@felix-kaestner let me implement some more on this PR and head back to you when I am finished. For now I already commited the changes that were commitable

2021-03-26 19:52 UTC, felix-kaestner commented on pkg/blockchain/block.go
> +func (block *Block) AccountBalance(p secp256k1.PublicKeyHexString) int64 {
Makes sense 👍

2021-03-26 19:52 UTC, felix-kaestner commented on pkg/blockchain/block.go
> +	ParentID *encryption.SHA256HexString `json:"parentID" sign:"yes"`
That is correct.

2021-03-26 19:54 UTC, felix-kaestner commented on pkg/color/color.go
> +}
Ok, so we can simply remove it then?

2021-03-26 19:55 UTC, felix-kaestner commented
@PhilippMatthes Sounds good to me.

2021-03-26 20:54 UTC, PhilippMatthes commented on pkg/blockchain/block.go
> +func (block *Block) AccountBalance(p secp256k1.PublicKeyHexString) int64 {
This is also from the NXT Whitepaper, I thought it made more sense than simply including a random arbitrary sender (such as a null address). Furthermore, the genesis account is free to use for everyone since it cannot make any new transactions or forges after the genesis block (supposing nobody sends more funds to the genesis account than initially in the network, which is possible technically)

2021-03-26 20:56 UTC, PhilippMatthes commented on pkg/color/color.go
> +}
Yes, I will remove it

2021-03-27 10:09 UTC, PhilippMatthes commented on pkg/blockchain/repo.go
> +}
Here I would still prefer the struct based wrapper, since it encapsulates the methods for accessing blocks and transactions via the database. Since the repository takes the role of the blockchain's tail segment, I would prefer to link it within the blockchain over linking it via a static instance.

2021-03-27 10:44 UTC, PhilippMatthes commented on pkg/blockchain/tree.go
> +	Children []*BlockTree
Let's discuss this point in a personal meeting a bit further, because it is not that trivial to decide the correct way to handle the slice here. It potentially interferes with lock handling and other shenanigans.

2021-03-27 10:44 UTC, PhilippMatthes commented on pkg/blockchain/tree.go
> +	StemNodes *[]*BlockTree
Let's discuss this point in a personal meeting a bit further, because it is not that trivial to decide the correct way to handle the slice here.

2021-03-27 10:58 UTC, PhilippMatthes commented on pkg/blockchain/peer.go
> +func (service *P2PService) interpret(bytes []byte) {
Good idea, but I have actually no idea how to apply this here. Does the golang json library have a possibility to unmarshal a generic interface and then use that for the type switch? I am really not sure whether this is applicable here. Maybe you could propose a solution

2021-04-01 13:25 UTC, PhilippMatthes commented
@felix-kaestner I will merge this now, to deploy our first single test node which also runs the new dashboard, the PoS, block + transaction creation and signatures with ECDSA over secp256k1, and much more. Let's work further on the merged implementation, which can of course be improved and consolidated with many more things. Initially this branch was also just to do some `p2p-prototyping` and evolved into the main development branch. So I should have also merged it probably a bit earlier.

2021-04-01 13:25 UTC, merged